services:
  - type: web
    name: portel-backend
    env: node
    plan: free
    # Removed root: server so that both server and client folders are available
    buildCommand: cd server && npm install
    startCommand: node server/index.js
    branch: main
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: portel-db
          property: connectionString
      - key: NODE_VERSION
        value: 13.14.0

databases:
  - name: portel-db
    plan: free
    databaseName: portel
    user: portel_user
